#!/usr/bin/env ruby
# frozen_string_literal: true

root = File.expand_path("..", __dir__)
allocations_path = File.join(root, "src", "instruction-encoding-allocations.adoc")
instructions_path = File.join(root, "src", "instructions.adoc")
output_path = File.join(root, "INSTRUCTION_ENCODINGS.md")

attributes = {}
File.foreach(allocations_path) do |line|
  match = line.match(/^:([a-z0-9-]+):\s+(\S+)$/)
  attributes[match[1]] = match[2] if match
end

entries = []
File.read(instructions_path).scan(/^=== `([^`]+)`\n(.*?)(?=^=== `|\z)/m) do |name, section|
  diagram = section.lines.find { |line| line.start_with?('{"reg":') }
  unless diagram
    next if section.include?("This specification does not assign an instruction encoding.")

    abort "#{name} has no WaveDrom encoding"
  end

  mnemonic = section[/Mnemonic::\n`([^`]+)`/, 1]
  abort "#{name} has no mnemonic" unless mnemonic

  position = 0
  mask = 0
  match_value = 0
  fields = []

  diagram.scan(/"bits":(\d+),"name":\s*(\{[^}]+\}|"[^"]+"|0x[0-9a-f]+|\d+)/) do |width_text, token|
    width = width_text.to_i
    lo = position
    hi = position + width - 1

    if token.start_with?('"')
      fields << { kind: :operand, name: token[1...-1], width: width, hi: hi, lo: lo }
    else
      attribute = token[/\A\{([^}]+)\}\z/, 1]
      value_text = attribute ? attributes.fetch(attribute) : token
      value = value_text.start_with?("0x") ? value_text.to_i(16) : value_text.to_i
      abort "#{name} value #{value_text} does not fit bits #{hi}:#{lo}" if value >= (1 << width)

      field_mask = ((1 << width) - 1) << lo
      mask |= field_mask
      match_value |= value << lo
      fields << { kind: :fixed, value: value, attribute: attribute, width: width, hi: hi, lo: lo }
    end
    position += width
  end

  abort "#{name} encoding is #{position} bits, expected 32" unless position == 32
  src1 = fields.find { |field| field[:hi] == 19 && field[:lo] == 15 }
  src2 = fields.find { |field| field[:hi] == 24 && field[:lo] == 20 }
  format = if src2[:kind] == :operand
             "R3"
           elsif src1[:kind] == :operand
             "R2"
           else
             "R1"
           end
  entries << { name: name, mnemonic: mnemonic, fields: fields, mask: mask,
               value: match_value, format: format }
end

overlaps = entries.combination(2).select do |left, right|
  common_mask = left[:mask] & right[:mask]
  ((left[:value] ^ right[:value]) & common_mask).zero?
end
exact_duplicates, partial_overlaps = overlaps.partition do |left, right|
  left[:mask] == right[:mask] && left[:value] == right[:value]
end

range = lambda do |field|
  field[:hi] == field[:lo] ? field[:hi].to_s : "#{field[:hi]}:#{field[:lo]}"
end

hex_field = lambda do |field|
  digits = [(field[:width] + 3) / 4, 1].max
  rendered = "`[#{range.call(field)}]=0x#{field[:value].to_s(16).rjust(digits, '0')}`"
  field[:attribute] ? "#{rendered} (`#{field[:attribute]}`)" : rendered
end

escape = ->(text) { text.to_s.gsub("|", "\\|") }

lines = []
lines << "# AME instruction encoding table"
lines << ""
lines << "> Generated by `ruby scripts/generate-instruction-encoding-table.rb` from " \
         "`src/instructions.adoc` and `src/instruction-encoding-allocations.adoc`. Do not edit manually."
lines << ""
lines << "The canonical decoder test is `(instruction_word & mask) == match`. " \
         "Fixed fields are listed from most-significant to least-significant bits."
lines << ""
lines << "## Collision audit"
lines << ""
lines << "| Check | Count |"
lines << "|---|---:|"
lines << "| Instructions | #{entries.length} |"
entries.group_by { |entry| entry[:format] }.sort.each do |format, members|
  lines << "| #{format} encodings | #{members.length} |"
end
lines << "| Exact duplicate decode patterns | #{exact_duplicates.length} |"
lines << "| Partial decode-space overlaps | #{partial_overlaps.length} |"

unless overlaps.empty?
  lines << ""
  lines << "| Type | Instruction A | Instruction B |"
  lines << "|---|---|---|"
  exact_duplicates.each { |a, b| lines << "| Exact duplicate | `#{a[:name]}` | `#{b[:name]}` |" }
  partial_overlaps.each { |a, b| lines << "| Partial overlap | `#{a[:name]}` | `#{b[:name]}` |" }
end

lines << ""
lines << "## Format allocation policy"
lines << ""
lines << "Every encoding retains `funct7[31:25]`, `funct3[14:12]`, and " \
         "`opcode[6:0]`. R2 converts only `src2[24:20]` to `xfunct5`; R1 also " \
         "converts `src1[19:15]`, yielding `xfunct10`. All instructions use " \
         "`funct3=000`; R0 is not defined."
lines << ""
lines << "A `(funct7, funct3, opcode)` bank belongs to only one format. This rule " \
         "prevents a more-specific R1/R2 pattern from being hidden inside an R2/R3 decode."
lines << "R3 uses `funct7=0x00..0x50` and `funct7=0x58..0x60`. R2 uses " \
         "`funct7=0x51` with `xfunct5=0..31` except the reserved value `0x09`, " \
         "before continuing at `funct7=0x52`; R1 uses `funct7=0x53` with " \
         "`xfunct10=0..3`. Values `0x54..0x57` and `0x61..0x7f` remain free."

lines << ""
lines << "## All instruction encodings"
lines << ""
lines << "| # | Format | Instruction | Mnemonic | Operand fields | Function/fixed fields | Mask | Match |"
lines << "|---:|---|---|---|---|---|---|---|"

entries.each_with_index do |entry, index|
  operands = entry[:fields].select { |field| field[:kind] == :operand }
                          .sort_by { |field| -field[:hi] }
                          .map { |field| "`#{field[:name]}[#{range.call(field)}]`" }
                          .join("; ")
  fixed = entry[:fields].select { |field| field[:kind] == :fixed }
                       .sort_by { |field| -field[:hi] }
                       .map { |field| hex_field.call(field) }
                       .join("; ")
  lines << format(
    "| %d | %s | `%s` | `%s` | %s | %s | `0x%08x` | `0x%08x` |",
    index + 1,
    entry[:format],
    escape.call(entry[:name]),
    escape.call(entry[:mnemonic]),
    operands,
    fixed,
    entry[:mask],
    entry[:value]
  )
end

generated = "#{lines.join("\n")}\n"
if ARGV == ["--check"]
  current = File.exist?(output_path) ? File.read(output_path) : ""
  abort "INSTRUCTION_ENCODINGS.md is stale; run ruby scripts/generate-instruction-encoding-table.rb" unless current == generated

  puts "checked instruction encoding table: #{entries.length} entries are current"
elsif ARGV.empty?
  File.write(output_path, generated)
  puts "wrote #{output_path} with #{entries.length} instruction encodings"
else
  abort "usage: #{$PROGRAM_NAME} [--check]"
end
